utc_opta:
    resource: "@UTCOptaBundle/Resources/config/routing.yml"
    prefix:   /

utc_scarf:
    resource: "@UTCScarfBundle/Resources/config/routing.yml"
    prefix:   /

utc_stats:
    resource: "@UTCStatsBundle/Resources/config/routing.yml"
    prefix:   /stats

